### ISSUE TITLE
Go Module Section ?

### ISSUE THREAD

**Issue by Thammachart** [hoanhan101/ultimate-go#21]
A lot of Go Projects are now moving to new dependency management system: Go Module

- Go Module would be promoted instead of GOPATH (*GOPATH would still be there for backward-compatibility*)
- This Feature will be finalized in soon-to-be Go 1.14.

Is there any plan for it, or it need further discussion?

https://blog.golang.org/using-go-modules
https://github.com/golang/go/wiki/Modules

**Comment by hoanhan101** [comment]
I don't have any plan for adding Go Module to this guide yet, though I agree it would be very helpful fo Go learners. If you have any idea or want to contribute to this guide, feel free to do so. I am more than happy to take a look.

**Comment by Thammachart** [comment]
I'm not well versed in Go myself, especially when It comes to new bleeding-edge features like this, but I'm interested in experiments and contribution. 

For me I think this feature need more time to mature to squeeze out edge cases and there are topics that need to verify in more practical use like major version change in sub-directory.

**Comment by hoanhan101** [comment]
Added link to Go Modules original blog post [here](6cc0bcc4e96ce7093c2bc22b225b0f840fe96685) as it already explains pretty clearly on how to use it.
