### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by lucasgsanchez** [hoanhan101/ultimate-go#29]
This is not an issue, just want to say thanks. Thank you for compiling this information. I will have this repo in my favorites and share it with anyone asking something about go. Thank you so very much.

**Comment by joicemjoseph** [comment]
I also want to thank you. This is a really beautiful repo. I am reading epub format. keep rocking!

**Comment by filirnd** [comment]
> I also want to thank you. This is a really beautiful repo. I am reading epub format. keep rocking!

Thank you for this. One question where do i get the epub format?

**Comment by joicemjoseph** [comment]
friend compiled into an ebook and shared with me.

**Comment by hoanhan101** [comment]
Thanks for all the support. I really appreciate it!

**Comment by lvtwoodpecker** [comment]
Thank you for making this! It's really helpful -- go Pokemon go!

**Comment by lvtwoodpecker** [comment]
Thank you for making this! It's really helpful -- go go go!

**Comment by filirnd** [comment]
> friend compiled into an ebook and shared with me.

Can you share with us compiling method ?

**Comment by cjmz** [comment]
> friend compiled into an ebook and shared with me.

Plllls, share with us :)

And thanks y'all for this repo.

**Comment by skovtunenko** [comment]
awesome repo! thank you for your efforts!

**Comment by bgradis** [comment]
Thank you, and yes, I also would like to have an e-book

**Comment by hoanhan101** [comment]
[I've put together an ebook here! Happy reading!](https://gumroad.com/l/bpUYF)

**Comment by nicewook** [comment]
Thank you. 
It's easy to read but doesn't miss any important information. 
I am thinking to have `study group` with your PDF book, and also translate to Korean with my study mate, though I am not guarantee the quality. 

Of course not for the monetary reason, but for the Korean how would get helped with `Korean` translated version of this book.
If you think it is okay, could you guide me how to do that?  

Thanks in advance

**Comment by hoanhan101** [comment]
Thanks for reaching out @nicewook. I like your idea. One thing you could do is to come up with a rough plan on how do to so and send it to me. We can work together then and validate it.

**Comment by nicewook** [comment]
> Thanks for reaching out @nicewook. I like your idea. One thing you could do is to come up with a rough plan on how do to so and send it to me. We can work together then and validate it.

Let me share you a brief plan. 
## Pre-Preparation
- Personal reading
- Make agreement with you for the rough rule
- Set the tool(GitHub, Google Docs, etc.) accordingly original text format (PDF, Markdown, or Google Docs?)

## Preparation
- Make rule and schedule for the translation 
- Gather study member and share the rules

## Study and Translation concurrently
## Study
- 8 to 10 weeks, every Tuesday night 07:30PM-09:30PM in Korean Time (Online with Zoom)
## Translation 
- Pre-translation: English to Google translation
- Every twe weeks, three times (means 6 or more weeks)
	1) the first week. one person in charge translate each part who is in charge, and PR(pull request)
	2) the second week. At least 2 reviewer check the PR and merge 

If possible, I'd like to have a channel to communicate with you. anything you like (ex. email, messenger, etc.)

**Comment by gmlwo530** [comment]
Thank you for your efforts! This repo is awesome!

**Comment by hoanhan101** [comment]
Feel free to reach out via the email I have in my profile, @nicewook.
