### ISSUE TITLE
Misunderstanding in data structure alignment

### ISSUE THREAD

**Issue by mightymatth** [hoanhan101/ultimate-go#33]
https://github.com/hoanhan101/ultimate-go/blob/3fb5ca6b658e32734f35a17e35d2809ac89b7910/go/language/struct.go#L29-L34

The first rule's statements are really hard to comprehend if it's your first time dealing with data structure alignments. Please, correct me if I'm wrong.

> Every 2 bytes value must follow a 2 bytes boundary.

It is really hard sentence to start this explanation, because it does not imply what to do with other cases, e.g. if you put 1 byte value, it must be followed by 1 byte boundary, etc. The reader may not conclude that this implies even further for 2, 4, 8 byte values (I'm not sure for Go case, but this statement may depend on specific architecture). 

> Similarly, if it is a 4 bytes value then we will have a 3 bytes padding value. 

Here, you don't point out that you are referring on the same example with setting 1 byte value on the beginning of the 8 byte block. I was thinking that you just appended value of pi to complete explaining alignment in that specific struct

I don't say that something here is wrong, but it's hard to understand. Maybe it should be revisited or put some references like [this](https://en.wikipedia.org/wiki/Data_structure_alignment) to be easier to understand.

**Comment by hoanhan101** [comment]
Thanks for looking into this. I'm closing this as a no-op for now though feel free to open a pull request if needed!
