### ISSUE TITLE
There may be a slight oversight here, write "flag" as "float"

### ISSUE THREAD

**Issue by zhanyeye** [hoanhan101/ultimate-go#38]
In 49,  write "flag bool" as "float bool" 
https://github.com/hoanhan101/ultimate-go/blob/9bb393cb4ea5cbc98a7b1596d41cd589822e52cc/go/language/struct.go#L45-L50

**Comment by hoanhan101** [comment]
Fixed in https://github.com/hoanhan101/ultimate-go/commit/df235b1646c90d52ddbe8933413d6169ae565bcd
