### ISSUE TITLE
This fails in the current Go playground - https://play.golang.org

### ISSUE THREAD

**Issue by amitmurthy** [hoanhan101/ultimate-go#4]
https://github.com/hoanhan101/ultimate-go/blob/d53aafdf786ebc4d1905888654558bf4abb7fba7/go/language/constant.go#L66

The above line fails with `constant 9223372036854775807 overflows int` when executed at https://play.golang.org

**Comment by kutluhanmetin** [comment]
This is because of the Go Playground's 32-bit architecture. Take attention what is stated at line https://github.com/hoanhan101/ultimate-go/blob/d53aafdf786ebc4d1905888654558bf4abb7fba7/go/language/constant.go#L63.

**Comment by amitmurthy** [comment]
OK. My bad.
