### ISSUE TITLE
when TestParallelize added t.Parallel(), the output is not expected

### ISSUE THREAD

**Issue by izerobit** [hoanhan101/ultimate-go#45]
https://github.com/hoanhan101/ultimate-go/blob/master/go/testing/sub_test.go
test method: TestParallelize

**_before added output:_**
=== RUN   TestParallelize
    11_test.go:82: Given the need to test downloading different content.
--- PASS: TestParallelize (1.04s)
=== RUN   TestParallelize/statusok
    **11_test.go:90: 	Test: 0	When checking "https://www.baidu.com" for status code 200
    11_test.go:96: 	✓	Should be able to make the Get call.
    11_test.go:101: 	✓	Should receive a 200 status code.**
    --- PASS: TestParallelize/statusok (0.28s)
=== RUN   TestParallelize/statusnotfound
    11_test.go:90: 	Test: 1	When checking "http://rss.cnn.com/rss/cnn_topstorie.rss" for status code 404
    11_test.go:96: 	✓	Should be able to make the Get call.
    11_test.go:101: 	✓	Should receive a 404 status code.
    --- PASS: TestParallelize/statusnotfound (0.75s)
PASS

**_after added t.Parallel()_**
=== RUN   TestParallelize
    11_test.go:82: Given the need to test downloading different content.
--- PASS: TestParallelize (0.00s)
=== RUN   TestParallelize/statusok
=== PAUSE TestParallelize/statusok
=== CONT  TestParallelize/statusok
    **11_test.go:90: 	Test: 1	When checking "http://rss.cnn.com/rss/cnn_topstorie.rss" for status code 404
    11_test.go:96: 	✓	Should be able to make the Get call.
    11_test.go:101: 	✓	Should receive a 404 status code.**
    --- PASS: TestParallelize/statusok (1.00s)
=== RUN   TestParallelize/statusnotfound
=== PAUSE TestParallelize/statusnotfound
=== CONT  TestParallelize/statusnotfound
    11_test.go:90: 	Test: 1	When checking "http://rss.cnn.com/rss/cnn_topstorie.rss" for status code 404
    11_test.go:96: 	✓	Should be able to make the Get call.
    11_test.go:101: 	✓	Should receive a 404 status code.
    --- PASS: TestParallelize/statusnotfound (0.71s)
PASS

the bold text is the difference

**Comment by hoanhan101** [comment]
`11_test.go:90: Test: 1 When checking "http://rss.cnn.com/rss/cnn_topstorie.rss" for status code 404` on both changes look the same to me. I am not sure what's the difference anywhere else too. Can you elaborate?

**Comment by izerobit** [comment]
> `11_test.go:90: Test: 1 When checking "http://rss.cnn.com/rss/cnn_topstorie.rss" for status code 404` on both changes look the same to me. I am not sure what's the difference anywhere else too. Can you elaborate?

the difference is,  after add "t.Parallel()", 
the test case only output "... rss.cnn ... for status code 404" twice
it means no "... google ... for status code 200" test case run.

because for loop in golang, ` for i, tt := range tests {`  the tt's address always the same, so the test case only run the last data for many times, I commit a pull request just add `tt := tt` to fix it

you can use this test code for a simple difference
`func Test_test(t *testing.T) {

	data := []int{1,2}
	for _, v := range data{
		fmt.Printf("same %d, %v \n", &v, v)
		v := v
		fmt.Printf("diff %d, %v \n", &v, v)
	}
}`

**Comment by hoanhan101** [comment]
I see. Thanks so much for the fix. I'll go ahead and merge it.
