### ISSUE TITLE
Maybe some error in the pdf

### ISSUE THREAD

**Issue by huangbxaaa** [hoanhan101/ultimate-go#49]
What an amazing tutorial!! Thanks a lot.

At page 28 of the book about slice, there is a phrase:
> What is I do data:= string{}? Is it the same?

I think it should be  
`data := []string{}`
<img width="333" alt="截屏2020-09-19 下午3 38 24" src="https://user-images.githubusercontent.com/22412942/93661906-2c138c00-fa8e-11ea-8d3a-897eb56c1c51.png">

**Comment by hoanhan101** [comment]
Thanks a lot for pointing it out. I'll fix it in the next revision.
